# The URL the site will be built for
base_url = "http://www.mcs.st-andrews.ac.uk/pg/pure/Analysis/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[extra]
title = "Analysis Research Group"
